version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: echo "hello world"
workflows:
  version: 2
  test_build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
#
