name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "mike-test-key-vault" 
          secrets: 'google-api-key,google-default-client-id,google-default-client-secret'  
        id: myGetSecretAction # ID for secrets that you will reference
      - run: |
          echo ${{ steps.myGetSecretAction.outputs.google-api-key }}
          echo ${{ steps.myGetSecretAction.outputs.google-default-client-id }}
          echo ${{ steps.myGetSecretAction.outputs.google-default-client-secret }}